# Generated by Django 4.2 on 2026-02-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0003_alter_studentresult_id_alter_studymaterial_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
