# Generated by Django 4.2 on 2026-02-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0004_alter_studentresult_id_alter_studymaterial_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetStudentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('math_marks', models.FloatField()),
                ('physics_marks', models.FloatField()),
                ('cs_marks', models.FloatField()),
                ('avg_score', models.FloatField()),
                ('level', models.CharField(max_length=20)),
                ('math_norm', models.FloatField()),
                ('physics_norm', models.FloatField()),
                ('cs_norm', models.FloatField()),
                ('avg_norm', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
