# Generated by Django 4.2 on 2026-02-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0005_datasetstudentperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='semester',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='source',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
