# Generated by Django 4.2 on 2026-02-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0006_studymaterial_link_studymaterial_semester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('params', models.JSONField(default=dict)),
                ('metrics', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='material_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='topic',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
