# Generated by Django 4.2 on 2026-02-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0007_mlmodelrun_studymaterial_material_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSETrainingExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField()),
                ('subject', models.CharField(max_length=120)),
                ('hand', models.FloatField()),
                ('attendance', models.FloatField()),
                ('ct', models.FloatField()),
                ('midterm', models.FloatField()),
                ('cgpa_prev', models.FloatField()),
                ('final_marks', models.FloatField()),
                ('total', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
