# Generated by Django 4.2 on 2026-02-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0008_csetrainingexample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csetrainingexample',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='csetrainingexample',
            name='cgpa_prev',
        ),
        migrations.RemoveField(
            model_name='csetrainingexample',
            name='ct',
        ),
        migrations.RemoveField(
            model_name='csetrainingexample',
            name='hand',
        ),
        migrations.RemoveField(
            model_name='csetrainingexample',
            name='midterm',
        ),
        migrations.AddField(
            model_name='csetrainingexample',
            name='assignment_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='csetrainingexample',
            name='attendance_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='csetrainingexample',
            name='final_grade',
            field=models.CharField(default='F', max_length=5),
        ),
        migrations.AddField(
            model_name='csetrainingexample',
            name='midterm_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='csetrainingexample',
            name='previous_cgpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='csetrainingexample',
            name='quiz_marks',
            field=models.FloatField(default=0.0),
        ),
    ]
