# Generated by Django 4.2 on 2026-02-14 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ml_engine', '0010_update_studymaterial_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('academic', 'Academic Prediction'), ('burnout', 'Burnout Prediction'), ('duration', 'Study Duration'), ('learning_style', 'Learning Style'), ('anxiety', 'Anxiety Detection'), ('spaced_repetition', 'Spaced Repetition'), ('knowledge_gaps', 'Knowledge Gap Analysis'), ('content_recommender', 'Content Recommender'), ('trend_prediction', 'Trend Prediction'), ('adaptive_difficulty', 'Adaptive Difficulty'), ('drift_detection', 'Drift Detection')], max_length=50)),
                ('version', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('model_path', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('model_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='SpacedRepetitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('difficulty_rating', models.FloatField(default=2.5)),
                ('interval_days', models.IntegerField(default=1)),
                ('repetitions', models.IntegerField(default=0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('next_review_date', models.DateField()),
                ('last_review_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_mastered', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sr_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_review_date'],
                'unique_together': {('user', 'item_id')},
            },
        ),
        migrations.CreateModel(
            name='UploadedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='datasets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('duration_minutes', models.IntegerField()),
                ('completion_rate', models.FloatField()),
                ('break_count', models.IntegerField(default=0)),
                ('time_of_day', models.CharField(max_length=20)),
                ('day_of_week', models.CharField(max_length=20)),
                ('quiz_score', models.FloatField(blank=True, null=True)),
                ('retention_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpacedRepetitionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.IntegerField()),
                ('response_time_seconds', models.FloatField()),
                ('confidence', models.IntegerField(blank=True, null=True)),
                ('new_interval_days', models.IntegerField()),
                ('new_ease_factor', models.FloatField()),
                ('new_repetitions', models.IntegerField()),
                ('predicted_retention', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ml_engine.spacedrepetitionitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('academic', 'Academic Prediction'), ('burnout', 'Burnout Prediction'), ('duration', 'Study Duration'), ('learning_style', 'Learning Style'), ('anxiety', 'Anxiety Detection'), ('spaced_repetition', 'Spaced Repetition'), ('knowledge_gaps', 'Knowledge Gap Analysis'), ('content_recommender', 'Content Recommender'), ('trend_prediction', 'Trend Prediction'), ('adaptive_difficulty', 'Adaptive Difficulty')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_features', models.JSONField(default=dict)),
                ('prediction_result', models.JSONField(default=dict)),
                ('response_time_ms', models.FloatField()),
                ('model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ml_engine.mlmodelversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('trend', models.CharField(choices=[('Improving', 'Improving'), ('Stable', 'Stable'), ('Declining', 'Declining')], max_length=20)),
                ('change_percent', models.FloatField()),
                ('confidence', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('data_points', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_trends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningStyleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual_score', models.FloatField(default=0.0)),
                ('auditory_score', models.FloatField(default=0.0)),
                ('reading_score', models.FloatField(default=0.0)),
                ('kinesthetic_score', models.FloatField(default=0.0)),
                ('primary_style', models.CharField(choices=[('visual', 'Visual'), ('auditory', 'Auditory'), ('reading', 'Reading/Writing'), ('kinesthetic', 'Kinesthetic'), ('multimodal', 'Multimodal')], max_length=20)),
                ('confidence', models.FloatField()),
                ('study_habits', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_style_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGapRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('concept', models.CharField(max_length=200)),
                ('current_level', models.FloatField()),
                ('target_level', models.FloatField()),
                ('gap_size', models.FloatField()),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('estimated_hours', models.FloatField()),
                ('is_addressed', models.BooleanField(default=False)),
                ('addressed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_gaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataDriftLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=50)),
                ('has_drift', models.BooleanField()),
                ('drift_score', models.FloatField()),
                ('drift_features', models.JSONField(default=list)),
                ('reference_accuracy', models.FloatField(blank=True, null=True)),
                ('current_accuracy', models.FloatField(blank=True, null=True)),
                ('recommendation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=100)),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('like', 'Like'), ('bookmark', 'Bookmark'), ('complete', 'Complete'), ('rate', 'Rate')], max_length=20)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BurnoutHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(max_length=20)),
                ('risk_score', models.FloatField()),
                ('confidence', models.FloatField()),
                ('top_factors', models.JSONField(default=list)),
                ('avg_daily_study_hours', models.FloatField()),
                ('consecutive_study_days', models.IntegerField()),
                ('sleep_hours', models.FloatField()),
                ('days_until_exam', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burnout_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnxietyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anxiety_level', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], max_length=20)),
                ('anxiety_score', models.FloatField()),
                ('confidence', models.FloatField()),
                ('contributing_factors', models.JSONField(default=list)),
                ('days_until_exam', models.FloatField()),
                ('target_score', models.FloatField()),
                ('previous_exam_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anxiety_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentLearningState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('current_difficulty', models.FloatField(default=5.0)),
                ('recent_success_rate', models.FloatField(default=0.5)),
                ('streak', models.IntegerField(default=0)),
                ('total_problems_attempted', models.IntegerField(default=0)),
                ('total_correct', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=60.0)),
                ('learning_rate', models.FloatField(default=0.01)),
                ('plateaus', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'subject')},
            },
        ),
        migrations.AddIndex(
            model_name='predictionlog',
            index=models.Index(fields=['user', 'model_type'], name='ml_engine_p_user_id_904b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='predictionlog',
            index=models.Index(fields=['created_at'], name='ml_engine_p_created_ffc5fa_idx'),
        ),
        migrations.AddIndex(
            model_name='contentinteraction',
            index=models.Index(fields=['user', 'content_id'], name='ml_engine_c_user_id_eb01dd_idx'),
        ),
    ]
