# Generated by Django 4.2 on 2026-02-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_engine', '0011_mlmodelversion_spacedrepetitionitem_uploadeddataset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddataset',
            name='checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='uploadeddataset',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
