# Generated by Django 4.2 on 2026-02-14 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ml_engine', '0012_uploadeddataset_checksum_uploadeddataset_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('regression', 'Final Marks Regression'), ('classification', 'Final Grade Classification')], max_length=20)),
                ('algorithm', models.CharField(max_length=80)),
                ('version', models.CharField(max_length=40)),
                ('model_path', models.CharField(max_length=255)),
                ('preprocessor_path', models.CharField(blank=True, max_length=255)),
                ('label_encoder_path', models.CharField(blank=True, max_length=255)),
                ('feature_columns', models.JSONField(default=list)),
                ('target_column', models.CharField(max_length=80)),
                ('metrics', models.JSONField(default=dict)),
                ('confusion_matrix', models.JSONField(blank=True, default=list)),
                ('classification_report', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='csetrainingexample',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='datasetstudentperformance',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='uploadeddataset',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='csetrainingexample',
            name='student_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='csetrainingexample',
            name='uploaded_dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_examples', to='ml_engine.uploadeddataset'),
        ),
        migrations.AddField(
            model_name='datasetstudentperformance',
            name='assignment_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='datasetstudentperformance',
            name='attendance_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='datasetstudentperformance',
            name='final_grade',
            field=models.CharField(default='F', max_length=5),
        ),
        migrations.AddField(
            model_name='datasetstudentperformance',
            name='final_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='datasetstudentperformance',
            name='final_marks_norm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='datasetstudentperformance',
            name='midterm_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='datasetstudentperformance',
            name='previous_cgpa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='datasetstudentperformance',
            name='previous_cgpa_norm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='datasetstudentperformance',
            name='quiz_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='datasetstudentperformance',
            name='semester',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='datasetstudentperformance',
            name='student_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='datasetstudentperformance',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='datasetstudentperformance',
            name='uploaded_dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_rows', to='ml_engine.uploadeddataset'),
        ),
        migrations.AddField(
            model_name='uploadeddataset',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='uploadeddataset',
            name='train_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadeddataset',
            name='trained_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='csetrainingexample',
            index=models.Index(fields=['semester', 'subject'], name='ml_engine_c_semeste_359fa7_idx'),
        ),
        migrations.AddIndex(
            model_name='csetrainingexample',
            index=models.Index(fields=['final_grade'], name='ml_engine_c_final_g_5de655_idx'),
        ),
        migrations.AddIndex(
            model_name='csetrainingexample',
            index=models.Index(fields=['student_id'], name='ml_engine_c_student_2450bd_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetstudentperformance',
            index=models.Index(fields=['semester', 'subject'], name='ml_engine_d_semeste_dfd8e0_idx'),
        ),
        migrations.AddIndex(
            model_name='datasetstudentperformance',
            index=models.Index(fields=['student_id'], name='ml_engine_d_student_a3cc10_idx'),
        ),
        migrations.AddConstraint(
            model_name='csetrainingexample',
            constraint=models.UniqueConstraint(fields=('uploaded_dataset', 'student_id', 'semester', 'subject'), name='uniq_training_student_sem_subject'),
        ),
        migrations.AddConstraint(
            model_name='datasetstudentperformance',
            constraint=models.UniqueConstraint(fields=('uploaded_dataset', 'student_id', 'semester', 'subject'), name='uniq_dataset_student_sem_subject'),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='trained_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainedmodel',
            name='trained_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trained_models', to='ml_engine.uploadeddataset'),
        ),
        migrations.AddIndex(
            model_name='trainedmodel',
            index=models.Index(fields=['task_type', 'is_active'], name='ml_engine_t_task_ty_b21596_idx'),
        ),
        migrations.AddIndex(
            model_name='trainedmodel',
            index=models.Index(fields=['version'], name='ml_engine_t_version_998922_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainedmodel',
            constraint=models.UniqueConstraint(fields=('task_type', 'version'), name='uniq_task_type_version'),
        ),
    ]
