# Generated by Django 4.2 on 2026-02-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0004_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
