# Generated by Django 4.2 on 2026-02-04 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userpanel', '0005_alter_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='average_score',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cluster_label',
        ),
        migrations.RemoveField(
            model_name='student',
            name='english_marks',
        ),
        migrations.RemoveField(
            model_name='student',
            name='science_marks',
        ),
        migrations.AddField(
            model_name='student',
            name='avg_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='cs_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='physics_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='math_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StudentResultHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math_marks', models.IntegerField()),
                ('physics_marks', models.IntegerField()),
                ('cs_marks', models.IntegerField()),
                ('avg_score', models.FloatField()),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
