# Generated by Django 4.2 on 2026-02-04 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userpanel', '0006_remove_student_average_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('title', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userpanel.semester')),
            ],
            options={
                'ordering': ('semester__number', 'name'),
                'unique_together': {('semester', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StudentSubjectPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midterm_marks', models.PositiveSmallIntegerField(default=0)),
                ('final_marks', models.PositiveSmallIntegerField(default=0)),
                ('total', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userpanel.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userpanel.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('semester__number', 'subject__name'),
                'unique_together': {('user', 'semester', 'subject')},
            },
        ),
    ]
