# Generated by Django 4.2 on 2026-02-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0007_semester_subject_studentsubjectperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubjectperformance',
            name='attendance_marks',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentsubjectperformance',
            name='ct_marks',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentsubjectperformance',
            name='hand_marks',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
