# Generated by Django 4.2 on 2026-02-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0008_studentsubjectperformance_attendance_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cgpa',
            field=models.FloatField(default=0.0),
        ),
    ]
