# Generated by Django 4.2 on 2026-02-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0009_student_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubjectperformance',
            name='final_pred',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='studentsubjectperformance',
            name='prob_a',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='studentsubjectperformance',
            name='prob_aplus',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='studentsubjectperformance',
            name='total_pred',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='studentsubjectperformance',
            name='final_marks',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
