# Generated by Django 4.2 on 2026-02-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0010_studentsubjectperformance_final_pred_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubjectperformance',
            name='attendance_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='studentsubjectperformance',
            name='predicted_grade',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='studentsubjectperformance',
            name='prob_fail',
            field=models.FloatField(default=0.0),
        ),
    ]
