# Generated by Django 4.2 on 2026-02-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_faceprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaceProfile',
        ),
    ]
